name: restfill_api
description: A server app using the shelf package and Docker.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.1.3

dependencies:
  args: ^2.4.2
  dart_jsonwebtoken: ^2.12.1
  dotenv: ^4.2.0
  shelf: ^1.4.1
  shelf_router: ^1.1.4
  supabase: ^1.11.11

dev_dependencies:
  http: ^1.1.0
  lints: ^3.0.0
  shelf_hotreload: ^1.4.0
  test: ^1.24.9
