


create table
  users (
    id BIGINT NOT NULL unique GENERATED BY DEFAULT AS IDENTITY(START WITH 100000 INCREMENT BY 1) PRIMARY KEY,
    id_auth uuid NOT NULL unique,
    name varchar(150),
    create_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    title_position varchar(80),
    phone varchar(10),
    email varchar(100) unique,
    location varchar(150),
    birthday date,
    about text,
    image text,
    FOREIGN KEY (id_auth) REFERENCES auth.users(id)

  );


  -- ///////////////////////