


create table
  users (
    id BIGINT NOT NULL unique GENERATED BY DEFAULT AS IDENTITY(START WITH 100000 INCREMENT BY 1) PRIMARY KEY,
    id_auth uuid NOT NULL unique,
    name varchar(150),
    create_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    title_position varchar(80),
    phone varchar(10),
    email varchar(100) unique,
    location varchar(150),
    birthday date,
    about text,
    image text,
    FOREIGN KEY (id_auth) REFERENCES auth.users(id)

  );


  -- ///////////////////////


  create table
  social_media (
    id BIGINT NOT NULL unique GENERATED BY DEFAULT AS IDENTITY(START WITH 100 INCREMENT BY 1),
    user_id BIGINT NOT NULL,
    username text not null,
    social varchar(25) NOT NULL DEFAULT 'other'::text CHECK (social IN ('facebook','youtube', 'whatsapp', 'instagram', 'twitter', 'tiktok', 'telegram', 'snapchat','other')),
    FOREIGN KEY (user_id) REFERENCES users(id),
    PRIMARY KEY (user_id, social)
    
  )



    -- ///////////////////////

create table
  skills (
    id BIGINT NOT NULL unique GENERATED BY DEFAULT AS IDENTITY(START WITH 100 INCREMENT BY 1),
    user_id BIGINT NOT NULL,
    skill text not null ,
    FOREIGN KEY (user_id) REFERENCES users(id),
    PRIMARY KEY (id)
    
  )


  -- /////


  create table
  projects (
    id BIGINT NOT NULL unique GENERATED BY DEFAULT AS IDENTITY(START WITH 100 INCREMENT BY 1),
    user_id BIGINT NOT NULL,
    name text not null,
    description text NOT NULL ,
    state varchar(12) NOT NULL DEFAULT 'other'::text CHECK (state IN ('completed','processing','other')),
    FOREIGN KEY (user_id) REFERENCES users(id),
    PRIMARY KEY (id)
    
  )

